# Generated by Django 5.2.18 on 2026-10-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_sellerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
